package edu.iastate.cs472.proj1;

import java.io.FileNotFoundException;
import java.io.File;
import java.sql.SQLOutput;
import java.util.Scanner;

/**
 *  
 * @author
 *
 */

public class PuzzleSolver 
{
	/**
	 *  Read an initial state from the input file.  Solve the eight puzzle three times:
	 *  
	 *      1) The first solution allows single moves only and uses the heuristic based on the number
	 *         of mismatched tiles. 
	 *         
	 *      2) The second solution also allows single moves only but uses the heuristic based on the 
	 *         Manhattan distance. 
	 *         
	 *      3) The third solution allows single and double moves and uses the admissible heuristic 
	 *         designed by yourself.  
	 *         
	 *  Each solution is printed out as a sequence of states, generated by single/double moves, from the 
	 *  initial state to the goal state. If no solution exists, report it.  
	 * 
	 * @param args
	 * @throws FileNotFoundException if the input file does not exist 
	 * @throws IllegalArgumentException if the initial state from the file is not in the correct format
	 */
	public static void main(String[] args) throws FileNotFoundException, IllegalArgumentException
	{	
		// Read an initial board configuration from a file.a
		int[][] initialBoard = new int[3][3];

		try {
			File f = new File("8puzzle.txt");
			Scanner scnr = new Scanner(f);
			int row = 0;

			while (scnr.hasNextLine()) {
				String l = scnr.nextLine();
				String[] rowArr = l.split(" ");

				for (int i = 0; i < rowArr.length; i++) {
					initialBoard[row][i] = Integer.parseInt(rowArr[i]);
				}

				++row;
			}
			scnr.close();
		} catch(FileNotFoundException e) {
			System.out.println("could not read file");
			e.printStackTrace();
		}

		for (int r = 0; r < initialBoard.length; r++) {
			for (int c = 0; c < initialBoard[r].length; c++) {
				System.out.print(initialBoard[r][c] + " ");
			}
			System.out.println();
		}

		// Call EightPuzzle.solve8puzzle() to solve the puzzle.
		State initialState = new State(initialBoard);

//		EightPuzzle.solve8Puzzle(initialState);
		// You may make it interactive by repeatedly accepting puzzle files and print out 
		// solutions.  (No extra credit but good for debugging and for the user.)
		String fileNames[] = new String[] {"8Puzzle.txt"};
		// TODO


	}

}
